localPlanner:
  ros__parameters:
    omniDirGoalThre: -1.0
    omniDirDrive: true

pathFollower:
  ros__parameters:
    omniDirGoalThre: -1.0
    omniDirDrive: true
    yawRateGain: 3.0
    stopYawRateGain: 4.0
    maxYawRate: 120.0
    dirDiffThre: 0.35
    stopDisThre: 0.25
